# This workflow builds a Java project with Gradle, caches dependencies, and submits dependency information to GitHub.

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Required for Dependency Submission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # Setup Gradle with dependency caching
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs

      # Generates and submits a dependency graph to GitHub Dependency Submission API
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
